# Generated by Django 6.0.3 on 2026-03-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_aluno_m2m_usuarios_remove_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número com DDI e DDD, ex: 5511999999999', max_length=20, null=True, verbose_name='Telefone (WhatsApp)'),
        ),
    ]
