# Generated by Django 5.2.12 on 2026-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0007_agendaevento_add_inicio_termino_tem_anexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefacompleta",
            name="visivel",
            field=models.BooleanField(default=True),
        ),
    ]
